### ISSUE TITLE
need to import paths in experimentalFunctions.py

### ISSUE THREAD

**Issue by bryce-d-smith** [gretatuckute/ClosedLoop#17]
in description.
for line 78 in experimentalFunctions.py

also in runSystem.py, there is an unresolved reference to "Transcripts" in line 27 and 212, what is this?

and in streamFunctions.py def stop() needs to be changed to stop(self) i think.

also, thanks for creating this =)

**Comment by gretatuckute** [comment]
Hi Bryce, thank you for these comments!

The paths import has now been solved (changed variable to settings.expDay insteads instead of paths.expDay). 

The Transcript is for tracking and logging of print outputs. This has now been changed to use the sys module in Python (saved as a log file to the subject ID folder).

stop(self) has hereby been added.
